version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/tiktak-node

      # permissions:
      #   - object: "/home/ec2-user/tiktak-node"
      #     owner: ec2-user
      #     group: ec2-user
      #     type: directory

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user

  BeforeInstall:
    - location: scripts/dependencies.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 60
      runas: root
    - location: scripts/install.sh
      timeout: 60
      runas: ec2-user